Revert commit only use for limited test cases

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -147,66 +147,52 @@ commands:
               echo "No commit to GitHub"
             fi
   revert-commit:
-    description: To revert a commit on fail , it needs to have a REVERT trigger in commit message
+    description: >
+      To revert a commit on fail , it needs to have a REVERT trigger in commit message.
+      Can be useful in testing but not recommend for regular usage because you learn
+      from troubleshooting bugs and errors.
     parameters:
       commit_sha:
         type: string
+      commit_trigger:
+        type: boolean
+        default: true
     steps: 
-      # - checkout
-      # - add_ssh_keys:
-      #     fingerprints:
-      #       - "<copy-paste-fingerprint-here>"
+      - when:
+          condition: << parameters.commit_trigger >>
+          steps:
+            - add_ssh_keys:
+                fingerprints:
+                  - "43:08:ce:f6:6f:04:b8:d2:53:1b:0c:fd:19:8f:2f:cc"
+            - run: 
+                name: Revert last commit on fail
+                command: |
+                  commit_message=$(git log -1 HEAD --pretty=format:%s)
+                  if [[ $commit_message == *REVERT* ]]; then
+                    echo "Revert commit on Fail"
 
-      # SSH_CONFIG_DIR='/home/circleci/.ssh'
-      - run: 
-          name: Revert last commit on fail
-          command: |
-            commit_message=$(git log -1 HEAD --pretty=format:%s)
-            if [[ $commit_message == *REVERT* ]]; then
-            echo "Revert commit on Fail"
+                    printf "%s" 'github.com ssh-ed25519 43:08:ce:f6:6f:04:b8:d2:53:1b:0c:fd:19:8f:2f:cc' >> "$HOME/.ssh/known_hosts"
+                    if [ "${HOME}" = "/" ]
+                    then
+                      export HOME=$(getent passwd $(id -un) | cut -d: -f6)
+                    fi
+                    export GIT_SSH_COMMAND='ssh -i "$HOME/.ssh/id_ed25519" -o UserKnownHostsFile="$HOME/.ssh/known_hosts"'
+                    echo "Committing to GitHub"
 
-            echo "Using SSH Config Dir '$SSH_CONFIG_DIR'"
-            git --version 
+                    # use git+ssh instead of https
+                    git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
+                    git config --global gc.auto 0 || true
+                    git config --global user.email $USER_EMAIL
+                    git config --global user.name $USER_NAME
 
-            mkdir -p "$SSH_CONFIG_DIR"
-            chmod 0700 "$SSH_CONFIG_DIR"
+                    # Caution using reset: this may cause push issues as the reverted commit will not exist
+                    #git reset --hard <<parameters.commit_sha>> 
+                    #git push --force
 
-            printf "%s" 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
-            github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
-            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
-            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
-            gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
-            ' >> "$SSH_CONFIG_DIR/known_hosts"
-            chmod 0600 "$SSH_CONFIG_DIR/known_hosts"
-
-            rm -f "$SSH_CONFIG_DIR/id_rsa"
-            printf "%s" "$CHECKOUT_KEY" > "$SSH_CONFIG_DIR/id_rsa"
-            chmod 0600 "$SSH_CONFIG_DIR/id_rsa"
-            if (: "${CHECKOUT_KEY_PUBLIC?}") 2>/dev/null; then
-              rm -f "$SSH_CONFIG_DIR/id_rsa.pub"
-              printf "%s" "$CHECKOUT_KEY_PUBLIC" > "$SSH_CONFIG_DIR/id_rsa.pub"
-            fi
-
-            export GIT_SSH_COMMAND='ssh -i "$SSH_CONFIG_DIR/id_rsa" -o UserKnownHostsFile="$SSH_CONFIG_DIR/known_hosts"'
-
-            # use git+ssh instead of https
-            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
-            git config --global gc.auto 0 || true
-            git config --global user.email $USER_EMAIL
-            git config --global user.name $USER_NAME
-
-            # Caution using reset: this may cause push issues as the reverted commit will not exist
-            #git reset --hard <<parameters.commit_sha>> 
-            #git push --force
-
-            # This reverses last commit but does not delete that commit history
-            git revert --no-commit <<parameters.commit_sha>> 
-            git push --force
-      
-            #curl --request POST \
-            #  --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
-            #  --header "Circle-Token: ${CIRCLE_TOKEN}"
-            fi           
+                    # This reverses last commit but does not delete that commit history
+                    git revert --no-commit <<parameters.commit_sha>> 
+                    git push --force
+                  fi          
 # Similar to [skip ci] or [ci skip] in commit message
   cancel-workflow:
     description: Cancel workflow given a commit message to stop it being run automatically
