smoke test migrations rollback

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1474,6 +1474,93 @@ jobs:
             # cleanup
             rm -f <<pipeline.parameters.ans_inventory_file>>
           when: on_fail
+      - run:
+          name: Revert migrations
+          working_directory: ./backend
+          command: |
+            export TYPEORM_USERNAME=$(aws ssm get-parameter \
+                --name /aws/reference/secretsmanager/UdaPeopleDB \
+                --with-decryption --output text --query "Parameter.Value" | jq -r ."username")
+
+            export TYPEORM_PASSWORD=$(aws ssm get-parameter \
+                --name /aws/reference/secretsmanager/UdaPeopleDB \
+                --with-decryption --output text --query "Parameter.Value" | jq -r ."password")
+
+            export TYPEORM_DATABASE=$(aws ssm get-parameter \
+                --name /aws/reference/secretsmanager/UdaPeopleDB \
+                --with-decryption --output text --query "Parameter.Value" | jq -r ."dbname")
+
+            RDS_PORT=$(aws rds describe-db-instances \
+                --db-instance-identifier backendDB-<<pipeline.parameters.resourceID>> \
+                --output text --query "DBInstances[*].Endpoint.Port")
+
+            RDS_HOST=$(aws rds describe-db-instances \
+                --db-instance-identifier backendDB-<<pipeline.parameters.resourceID>> \
+                --output text --query "DBInstances[*].Endpoint.Address")
+            export TYPEORM_HOST=localhost
+            export TYPEORM_PORT=5532
+            export NODE_ENV=test
+            # check other environment variables
+            if [ -z "${TYPEORM_CONNECTION:-}" ]; then
+                echo "In order to use the Deploy backend job a TYPEORM_CONNECTION environment variable must be present."
+                exit 1
+            fi
+            if [ -z "${TYPEORM_ENTITIES:-}" ]; then
+                echo "In order to use the Deploy backend job a TYPEORM_ENTITIES environment variable must be present."
+                exit 1
+            fi
+            if [ -z "${TYPEORM_MIGRATIONS:-}" ]; then
+                echo "In order to use the Deploy backend job a TYPEORM_MIGRATIONS environment variable must be present."
+                exit 1
+            fi
+            if [ -z "${TYPEORM_MIGRATIONS_DIR:-}" ]; then
+                echo "In order to use the Deploy backend job a TYPEORM_MIGRATIONS_DIR environment variable must be present."
+                exit 1
+            fi
+
+            #SSH connection configuration
+            if [ "${HOME}" = "/" ]
+            then
+              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
+            fi
+            printf "%s QbM8rDBaZ9yajNovvO09gv+ks71u1c1y0C4S6Bt39CE" $EC2_HOST >> "$HOME/.ssh/known_hosts"
+            chmod 0600 "$HOME/.ssh/known_hosts"
+            if [ -f "$HOME/.ssh/id_ed25519" ]; then
+              rm -f "$HOME/.ssh/id_ed25519"
+            fi
+
+            #access ssh key from aws secrets
+            EC2_USER=$(aws ssm get-parameter \
+                --name /aws/reference/secretsmanager/UdaPeopleSSH \
+                --with-decryption --output text --query "Parameter.Value" | jq -r ."user")
+
+            EC2_HOST=$(aws --output text --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            ec2 describe-instances --filters Name='tag:Name',Values='backend-<<pipeline.parameters.resourceID>>') 
+
+            aws ssm get-parameter \
+                --name /aws/reference/secretsmanager/udapeople_ssh_key \
+                --with-decryption --output text --query "Parameter.Value" > "$HOME/.ssh/id_ed25519"
+
+            chmod 0700 "$HOME/.ssh/id_ed25519"
+            # ssh tunnel
+            ssh -4 -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=no -f -N -L $TYPEORM_PORT:$RDS_HOST:$RDS_PORT $EC2_USER@$EC2_HOST 
+            npm cache clean --force
+            npm i
+            npm run migrations:revert 
+
+            # cleanup
+            unset TYPEORM_USERNAME
+            unset TYPEORM_PASSWORD
+            unset TYPEORM_DATABASE
+            unset RDS_HOST
+            unset RDS_PORT
+            # check if tunnel is still live
+            TUNNEL_TEST=$(nc -z localhost 5532)
+            if [ $TUNNEL_TEST != '' ]; then
+              killall ssh &>/dev/null
+            fi
+            rm -f $HOME/.ssh/id_ed25519
+          when: on_fail
       - slack/notify:
           event: fail
           template: basic_fail_1
